site_name: Common metadata e-helse
repo_url: https://github.com/Direktoratet-for-e-helse/Common-metadata
repo_name: Direktoratet-for-e-helse/Common-metadata
nav:
    - Common metadata: README.md
    - Andre metadata for arkitekturbiblioteket: Arkbibl-metadata.md
    - Statusinformasjon: https://direktoratet-for-e-helse.github.io/Common-metadata/
theme:
  name: material
  logo: logo/ehelse-hvit.svg
  #custom_dir: material/.overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  favicon: logo/ehelse-hvit.png
  #icon:
  #  logo: logo